// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupersHerosCRM.Data;

#nullable disable

namespace SupersHerosCRM.Migrations
{
    [DbContext(typeof(SupersHerosCRMDbContext))]
    [Migration("20230522105147_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeroIncident", b =>
                {
                    b.Property<int>("HeroesId")
                        .HasColumnType("integer")
                        .HasColumnName("heroes_id");

                    b.Property<int>("IncidentsId")
                        .HasColumnType("integer")
                        .HasColumnName("incidents_id");

                    b.HasKey("HeroesId", "IncidentsId")
                        .HasName("pk_hero_incident");

                    b.HasIndex("IncidentsId")
                        .HasDatabaseName("ix_hero_incident_incidents_id");

                    b.ToTable("hero_incident", (string)null);
                });

            modelBuilder.Entity("SupersHerosCRM.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_heroes");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_heroes_id");

                    b.ToTable("Heroes", (string)null);
                });

            modelBuilder.Entity("SupersHerosCRM.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.ToTable("Incidents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Incendie"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Accident routier"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Accident fluvial"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Accident aérien"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Eboulement"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Invasion de serpents"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Fuite de gaz"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Manifestation"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Braquage"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Evasion d’un prisonnier"
                        });
                });

            modelBuilder.Entity("HeroIncident", b =>
                {
                    b.HasOne("SupersHerosCRM.Models.Hero", null)
                        .WithMany()
                        .HasForeignKey("HeroesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hero_incident_heroes_heroes_id");

                    b.HasOne("SupersHerosCRM.Models.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hero_incident_incidents_incidents_id");
                });
#pragma warning restore 612, 618
        }
    }
}
